language: go
sudo: false
go:
  - 1.8.x
  - 1.9.x

install:
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega/...
  - go get -u github.com/golang/dep/cmd/dep
  - export PATH=$PATH:$HOME/gopath/bin
  - dep ensure

before_script:
  - cd $GOPATH/src; mv ./github.com/mhmoudgmal/pdcli .
  - cd ./pdcli

script:
 - $HOME/gopath/bin/ginkgo -r

