[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  # based on branch (listbox) of (github.com/pdevine/termui)
  branch = "item-in-memory-data"
  name = "github.com/mhmoudgmal/termui"

[[constraint]]
  name = "gopkg.in/h2non/gock.v1"
  version = "1.0.7"
