[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  branch = "listbox"
  name = "github.com/pdevine/termui"

[[constraint]]
  name = "gopkg.in/h2non/gock.v1"
  version = "1.0.7"
